data<-read.delim("./data/household_power_consumption.txt", sep = ";")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
data<-subset(data, Date==as.Date("2007-02-01") | Date ==as.Date("2007-02-02"))
time<-paste(data$Date,data$Time)
time<-strptime(time, "%Y-%m-%d %H:%M:%S")
data$Time<-time
data[,3:9]<-apply(data[3:9],2,as.numeric)
par(mfrow=c(2,2), mar=c(4,4,4,4))
plot(data$Time,data$Global_active_power, type = "l", xlab="",ylab="Global Active Power",cex=0.1)
plot(data$Time, data$Voltage, type="l",xlab = "datetime",ylab = "Voltage", cex=0.1)
plot(data$Time,data$Sub_metering_1, type = "l", col="black", xlab="" ,ylab = "Energy sub metering", cex=0.1)
lines(data$Time,data$Sub_metering_2, col="red")
lines(data$Time,data$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"), cex=0.7, bty="n")
plot(data$Time, data$Global_reactive_power, xlab = "datetime", cex=0.1, type="l")